config/routes.rb
Rails.application.routes.draw do
  root 'page#index'
  get 'page/index'
  get '/about', to: 'page#about'
  get '/writing', to: 'page#writs'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
    render 'index'
  end
  def about
  end
  def writs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Winnie Wu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Roboto:300,400,500,700' %>
  </head>
  <body>
    <div class="top">
      <div class="name-title">
        <a href="<%= about_path %>">Winnie<br>Wu</a>
      </div>
      <div class="menu pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="menu--item pure-menu-item pure-menu-item-has-children pure-menu-allow-hover">
            <%= link_to('work', '/') %>
            <ul class="menu--submenu pure-menu-children">
              <li class="menu--subitem pure-menu-item">
                <a href="#">photo</a>
              </li>
              <li class="menu--subitem pure-menu-item">fine art</li>
            </ul>
          </li>
          <li class="menu--item pure-menu-item">
            <%= link_to('about', about_path) %>
          </li>
          <li class="menu--item pure-menu-item">
            <%= link_to('writs', writing_path) %>
          </li>
        </ul>
      </div>
    </div>
    <div class="app-body">
      <%= yield %>
    </div>
  </body>
</html>

app/views/page/index.html.erb
<% content_for(:body_attributes) do %>
    data-no-turbolink="true"
<% end %>

<div class="grid">
  <div class="gutter-sizer"></div>
  <% @images = Dir.glob("app/assets/images/portfolio/*.{gif,jpg,png}")
    @images.each do |image| %>
    <div class="grid-item">
    <%= image_tag image.gsub("app/assets/images/", ""), class: 'box-fit' %>
    </div>
   <% end %>
</div>